# Generated by Django 3.0.3 on 2020-03-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddRoom',
            fields=[
                ('room_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('room_size', models.CharField(blank=True, max_length=50, null=True)),
                ('room_facilities', models.CharField(blank=True, max_length=150, null=True)),
                ('room_price', models.IntegerField(blank=True, null=True)),
                ('capacity', models.CharField(max_length=20)),
                ('room_photo', models.ImageField(blank=True, null=True, upload_to='profile/')),
            ],
        ),
        migrations.CreateModel(
            name='CheckAvailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateTimeField(blank=True, null=True)),
                ('check_out_date', models.DateTimeField(blank=True, null=True)),
                ('room_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FillCostumerForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.CharField(blank=True, max_length=15, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_address', models.CharField(blank=True, max_length=100, null=True)),
                ('temporary_address', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('no_of_costumer', models.CharField(blank=True, max_length=50, null=True)),
                ('relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
