# Generated by Django 3.0.3 on 2020-03-15 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillcostumerform',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='addroom',
            name='room_no',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
